//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiningProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataMiningProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html&gt;
        ///
        ///&lt;!--HEAD--&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Christina&apos;s Favorite Stuff!&lt;/title&gt;
        ///
        ///     &lt;link rel = &quot;stylesheet&quot;
        ///        type = &quot;text/css&quot;
        ///        href = &quot;assignment1_style.css&quot; &gt; 
        ///
        ///    &lt;!--HEADER
        ///    --&gt;    
        ///    &lt;header id = &quot;myHeader&quot;&gt;
        ///        &lt;div class = &quot;unmoveableContainer&quot;&gt;
        ///        &lt;h1&gt;Hello.&lt;/h1&gt;
        ///    &lt;/div&gt;
        ///    &lt;/header&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///
        ///&lt;!--BODY--&gt;
        ///&lt;body&gt;
        ///    &lt;!--NAV--&gt;
        ///        &lt;nav id = &quot;navBar&quot;&gt;
        ///            &lt;div class = &quot;container&quot;&gt;
        ///                &lt;ul&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assignment1 {
            get {
                return ResourceManager.GetString("assignment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] python {
            get {
                object obj = ResourceManager.GetObject("python", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] python36 {
            get {
                object obj = ResourceManager.GetObject("python36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sum {
            get {
                object obj = ResourceManager.GetObject("sum", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
